# Generated by Django 5.0.1 on 2024-01-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart_category_order_product_orderdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
