# Generated by Django 5.0.1 on 2024-01-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_image_productimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image_url',
        ),
    ]
